import { createCronManager } from '../server'
// Virtual module generated by nuxt-cron during build — provides discovered job list
// @ts-expect-error — resolved by Nitro/Rollup at build time
import { __cronJobs, __cronOptions } from '#nuxt-cron-jobs'
import type { CronJobDefinition } from '../types'

export default defineNitroPlugin((nitroApp) => {
  const manager = createCronManager(__cronOptions)

  for (const [name, definition] of Object.entries<CronJobDefinition>(__cronJobs)) {
    manager.register(name, definition)
  }

  nitroApp.cronManager = manager

  const count = Object.keys(__cronJobs).length
  const names = Object.keys(__cronJobs).join(', ')
  console.info(`[nuxt-cron] ${count} job(s) registered${names ? ': ' + names : ''}`)

  nitroApp.hooks.hookOnce('close', () => {
    manager.destroy()
  })
})
